const express = require("express");
const router = express.Router();
const categoryRoutes = require("../../Controller/Category/script");
const upload = require("../../Middleware/upload/script");
const { authMiddleware, isAdmin } = require("../../Middleware/AuthMiddleware/script");
router.post("/addcategory", authMiddleware, isAdmin, upload.single("image"), categoryRoutes.createCategory);
router.get("/getcategory", authMiddleware, categoryRoutes.getCategory);
router.get("/getSingle/:id", authMiddleware, categoryRoutes.getSingleCategory);
router.put("/updateCategory/:id", authMiddleware, isAdmin, upload.single("image"), categoryRoutes.updateCategory);
router.delete("/deleteCategory/:id", authMiddleware, isAdmin, categoryRoutes.deleteCategory);
module.exports = router;